#!/bin/bash

source /usr/bin/TS

# toggle the mux to standby if dualtor and any mux active
if
[[ "$(sonic-cfggen -d -v DEVICE_METADATA.localhost.subtype | tr [:upper:] [:lower:])" == *"dualtor"* ]] &&
[[ $(show mux status | grep active | wc -l) > 0 ]];
then
  logger -t TSA -p user.info "Toggle all mux mode to standby"
  sudo config mux mode standby all
fi

if ! is_chassis_supervisor; then
  /usr/bin/TS TSA $1
  echo "Please execute 'config save' to preserve System mode in Maintenance after reboot or config reload"
else
  rexec all -c "TSA $1"
  echo "Please execute \"rexec all -c 'config save'\" to preserve System mode in Maintenance after reboot \
  or config reload on all linecards"s
fi

