#!/bin/bash

# toggle the mux to standby if dualtor and any mux active
if
[[ "$(sonic-cfggen -d -v DEVICE_METADATA.localhost.subtype | tr [:upper:] [:lower:])" == *"dualtor"* ]] &&
[[ $(show mux status | grep active | wc -l) > 0 ]];
then
  logger -t TSA -p user.info "Toggle all mux mode to standby"
  sudo config mux mode standby all
fi

if [ -f /etc/sonic/chassisdb.conf ]; then
  rexec all -c "TSA $1"
  echo "Please execute \"rexec all -c 'sudo config save -y'\" to preserve System mode in Maintenance after reboot \
  or config reload on all linecards"
else
  /usr/bin/TS TSA $1
  echo "Please execute 'sudo config save' to preserve System mode in Maintenance after reboot or config reload"
fi
